import { readFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { resolve, relative, sep, extname } from 'node:path';
import { execFileSync } from 'node:child_process';
import assert from 'node:assert/strict';
import { ATLAS_FILES, ATLAS_COUNTS } from '../src/game/assets.js';

const root=resolve('dist');
const walk=dir=>readdirSync(dir).flatMap(name=>{const file=resolve(dir,name);return statSync(file).isDirectory()?walk(file):[file];});
assert(existsSync(resolve(root,'sw.js')),'Run npm run build before npm run check.');
const files=walk(root),sw=readFileSync(resolve(root,'sw.js'),'utf8');
const match=sw.match(/^const CONFIG = (.+);$/m);
assert(match,'The production service worker must be generated by Vite. Run npm run build.');
const offline=JSON.parse(match[1]);
const local=url=>{
  const path=new URL(url,'https://game.example'+offline.base).pathname;
  assert(path.startsWith(offline.base),`Reference escapes the configured base: ${url}`);
  return resolve(root,decodeURIComponent(path.slice(offline.base.length))||'index.html');
};
let references=0;
for(const file of [...walk(resolve('src')),resolve('vite.config.js'),...files]){
  if(file.endsWith('.js'))execFileSync(process.execPath,['--check',file]);
}
for(const file of files.filter(file=>/\.(html|css)$/.test(file))){
  const content=readFileSync(file,'utf8');
  const pattern=file.endsWith('.html')?/(?:src|href)=["']([^"']+)["']/g:/url\(["']?([^"')\s]+)["']?\)/g;
  for(const match of content.matchAll(pattern)){
    const path=match[1];if(/^(?:https?:|data:|#)/.test(path))continue;
    assert(existsSync(local(path)),`Missing reference ${path} in ${file}`);references++;
  }
}
const cached=new Set(offline.files);
assert.equal(cached.size,offline.files.length,'Duplicate offline URLs');
assert(cached.has(offline.base));
for(const path of cached)assert(existsSync(local(path)),`Missing offline asset ${path}`);
for(const file of files){
  if(file===resolve(root,'sw.js'))continue;
  assert(cached.has(offline.base+relative(root,file).split(sep).join('/')),`Build output missing from offline cache: ${file}`);
}
const manifest=JSON.parse(readFileSync(resolve(root,'manifest.webmanifest')));
assert.equal(manifest.display,'standalone');assert.equal(manifest.start_url,'./');assert.equal(manifest.scope,'./');
for(const size of [192,512]){
  const icon=manifest.icons.find(icon=>icon.sizes===`${size}x${size}`);assert(icon,`Missing ${size}px app icon`);
  const png=readFileSync(local(icon.src));assert.equal(png.readUInt32BE(16),size);assert.equal(png.readUInt32BE(20),size);
}
const sprites=JSON.parse(readFileSync(resolve(root,'assets/sprites.json')));
for(const [key,name] of Object.entries(ATLAS_FILES)){
  const rects=sprites[name], [width,height]=sprites._sizes[name];
  assert.equal(rects.length,ATLAS_COUNTS[key]);
  assert(existsSync(resolve(root,`assets/${name}.webp`)),`Missing atlas ${name}`);
  for(const rect of rects){const [x,y,w,h]=rect;assert.equal(rect.length,4);assert(rect.every(Number.isFinite));assert(x>=0&&y>=0&&w>0&&h>0&&x+w<=width&&y+h<=height,`Out-of-bounds sprite in ${name}`);}
  if(key.endsWith('World'))for(const index of [0,1,2,3,4,5,16,17]){
    const surface=sprites._surfaces?.[name]?.[index];
    assert(surface?.length===3&&surface.every(Number.isFinite),`Missing landing anchors for ${name}:${index}`);
    const [left,top,right]=surface,[,,w,h]=rects[index];
    assert(left>=0&&right<=w&&right>left&&top>=0&&top<h,`Invalid landing anchors for ${name}:${index}`);
  }
}
for(const file of walk(resolve('src/styles'))){
  if(extname(file)!=='.css')continue;
  const css=readFileSync(file,'utf8');assert.equal([...css].filter(c=>c==='{').length,[...css].filter(c=>c==='}').length);
}
const css=readFileSync(resolve('src/styles/style.css'),'utf8');assert(css.includes('safe-area-inset-bottom'));assert(css.includes('orientation:landscape'));
const bytes=files.reduce((n,p)=>n+statSync(p).size,0);
assert(bytes<4_000_000,`Complete game is too large: ${bytes}`);
console.log(`Validated React/Vite output, ${references} local references, ${cached.size} offline URLs, app icons, sprite bounds, and JavaScript syntax.`);
console.log(`Complete uncompressed production payload: ${(bytes/1024).toFixed(0)} KiB.`);
